CREATE TABLE `confiscations` (
	`id` INT(10,0) NOT NULL AUTO_INCREMENT,
	`owner` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`officer` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`plate` VARCHAR(12) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`originaldate` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`garage` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=5
;